// text_effects  yes_no justify align  gap  size  shadow  radius                                
export const options = {
    blank: [
        { v: '', t: 'none' },
        { v: '', t: '' },
    ],
    symbol_mode: [
        { v: '', t: 'None' },
        { v: 'icons', t: 'Icons' },
        { v: 'num', t: 'Numbers' },
    ],
    icon_place: [
        { v: 'icn-bebore', t: 'Before Title' },
        { v: 'icn-after', t: 'After Title' },
        { v: 'icn-above', t: 'Above Title' },
        { v: 'icn-aside', t: 'Aside Left' },
    ],
    effects: [
        { v: '', t: 'none' },
        { v: 'e-shadow', t: 'shadow' },
        { v: 'e-inset', t: 'inset' },
        { v: 'e-glow ', t: 'glow' },
        { v: 'e-neon', t: 'neon' },
        { v: 'e-flame', t: 'flame' },
        { v: 'e-fire', t: 'fire' },
        { v: 'e-blur', t: 'blur' },
        { v: 'e-simple3d', t: 'simple3d' },
        { v: 'e-realistic3d', t: 'realistic3d' },
        { v: 'e-vegas', t: 'vegas' },
        { v: 'e-monument', t: 'monument' },
        { v: 'e-deep', t: 'deep' },
        { v: 'e-tactile', t: 'tactile' },
        { v: 'e-slight ', t: 'slight ' },
        { v: 'e-shadow-glow', t: 'shadow-glow' },
        { v: 'e-blue-shadow', t: 'blue-shadow' },
        { v: 'e-slight-shadow', t: 'slight-shadow' },
    ],
    wc: [
        { v: '', t: 'Auto' },
        { v: 'wc-1-5', t: '20%' },
        { v: 'wc-1-4', t: '25%' },
        { v: 'wc-1-3', t: '33%' },
        { v: 'wc-1-2', t: '50%' },
        { v: 'wc-1-1', t: '100%' },
    ],
    wi: [
        { v: '', t: 'Auto' },
        { v: 'w-1-5', t: '20%' },
        { v: 'w-1-4', t: '25%' },
        { v: 'w-1-3', t: '33%' },
        { v: 'w-1-2', t: '50%' },
        { v: 'w-1-1', t: '100%' },
    ],
    pos: [
        { v: 'p-r', t: 'Relative' },
        { v: 'p-a', t: 'Absolute' },
    ],
    ag: [
        { v: '', t: 'None' },
        { v: 'jag ga-fade-in', t: 'Fade In' },
    ],
    fw: [
        { v: '', t: 'Normal' },
        { v: 'fw-600', t: 'Bold' },
    ],
    tag: [
        { v: 'h1', t: 'Heading 1' },
        { v: 'h2', t: 'Heading 2' },
        { v: 'h3', t: 'Heading 3' },
        { v: 'h4', t: 'Heading 4' },
        { v: 'h5', t: 'Heading 5' },
        { v: 'h6', t: 'Heading 6' },
    ],
    but_style: [
        { v: '', t: 'Simple Link' },
        { v: 'but-normal', t: 'Normal' },
        { v: 'but-small', t: 'Small' },
        { v: 'but-large', t: 'Large' },
        { v: 'but-extra-large', t: 'Extra Large' }
    ],
    p: [
        { v: '', t: 'None' },
        { v: 'p-05', t: '0.5rem' },
        { v: 'p-1', t: '1rem' },
        { v: 'p-2', t: '2rem' },
        { v: 'p-3', t: '3rem' },
        { v: 'p-4', t: '4rem' },
        { v: 'p-5', t: '5rem' },
    ],
    g: [
        { v: '', t: 'None' },
        { v: 'g-05', t: '0.5rem' },
        { v: 'g-1', t: '1rem' },
        { v: 'g-2', t: '2rem' },
        { v: 'g-3', t: '3rem' },
        { v: 'g-4', t: '4rem' },
        { v: 'g-5', t: '5rem' },
    ],
    m: [
        { v: '', t: 'None' },
        { v: 'mv-05', t: '0.5rem' },
        { v: 'mv-1', t: '1rem' },
        { v: 'mv-2', t: '2rem' },
        { v: 'mv-3', t: '3rem' },
        { v: 'mv-4', t: '4rem' },
        { v: 'mv-5', t: '5rem' },
    ],
    ba: [
        { v: 'ba-s', t: 'Scroll' },
        { v: 'ba-f', t: 'Fixed' },
    ],
    bp: [
        { v: 'bp-cc', t: 'Center Center' },
        { v: 'bp-ct', t: 'Center Top' },
        { v: 'bp-cb', t: 'Center Bottom' },
        
    ],
    yes_no: [
        { v: true, t: 'Yes' },
        { v: false, t: 'No' },
    ],
    w: [
        { v: 'w-container', t: 'Container 1200' },
        { v: 'w-fluid', t: 'Fluid(gaps left/right)' },
        { v: 'w-full', t: 'Full Width(no gaps)' },
    ],
    jc: [
        { v: 'jc-c', t: 'Center' },
        { v: 'jc-b', t: 'Space-between' },
        { v: 'jc-s', t: 'Start' },
        { v: 'jc-e', t: 'End' },
        { v: 'jc-a', t: 'Space-around' },
        { v: 'jc-ev', t: 'Space-evenly' },
    ],
    ai: [
        { v: 'ai-s', t: 'Start' },
        { v: 'ai-e', t: 'End' },
        { v: 'ai-b', t: 'Baseline' },
        { v: 'ai-st', t: 'Stretch' },
        { v: 'ai-c', t: 'Center' },
    ],
    g: [
        { v: 'g-05', t: '0.5 rem' },
        { v: 'g-1', t: '1 rem' },
        { v: 'g-2', t: '2 rem' },
        { v: 'g-3', t: '3 rem' },
    ],
    'fd': [
        { v: 'fd-r', t: 'Row' },
        { v: 'fd-rr', t: 'Row Reverse' },
        { v: 'fd-c', t: 'Column' },
        { v: 'fd-cr', t: 'Column Reverse' },
    ],
    size: [
        { v: 'fd-r', t: 'Row' },
        { v: 'fs-8', t: '0.8 rem' },
        { v: 'fs-9', t: '0.9 rem' },
        { v: 'fs-10', t: '1 rem' },
        { v: 'fs-11', t: '1.1 rem' },
        { v: 'fs-12', t: '1.2 rem' },
        { v: 'fs-13', t: '1.3 rem' },
        { v: 'fs-14', t: '1.4 rem' },
        { v: 'fs-15', t: '1.5 rem' },
        { v: 'fs-16', t: '1.6 rem' },
        { v: 'fs-17', t: '1.7 rem' },
        { v: 'fs-18', t: '1.8 rem' },
        { v: 'fs-19', t: '1.9 rem' },
        { v: 'fs-20', t: '2 rem' },
        { v: 'fs-21', t: '2.1 rem' },
        { v: 'fs-22', t: '2.2 rem' },
        { v: 'fs-23', t: '2.3 rem' },
        { v: 'fs-24', t: '2.4 rem' },
        { v: 'fs-25', t: '2.5 rem' },
        { v: 'fs-26', t: '2.6 rem' },
        { v: 'fs-27', t: '2.7 rem' },
        { v: 'fs-28', t: '2.8 rem' },
        { v: 'fs-29', t: '2.9 rem' },
        { v: 'fs-30', t: '3 rem' },
        { v: 'fs-31', t: '3.1 rem' },
        { v: 'fs-32', t: '3.2 rem' },
        { v: 'fs-33', t: '3.3 rem' },
        { v: 'fs-34', t: '3.4 rem' },
        { v: 'fs-35', t: '3.5 rem' },
    ],
    bs: [
        { v: '', t: 'none' },
        { v: 'bs-1', t: 'Depth 1' },
        { v: 'bs-2', t: 'Depth 2' },
        { v: 'bs-3', t: 'Depth 3' },
        { v: 'bs-4', t: 'Depth 4' },
        { v: 'bs-5', t: 'Depth 5' },
        { v: 'bs-5', t: 'Depth 6' },
        { v: 'bs-7', t: 'Depth 7' },
    ],
    radius: [
        { v: '', t: 'none' },
        { v: 'br-1', t: '1px' },
        { v: 'br-2', t: '2px' },
        { v: 'br-3', t: '3px' },
        { v: 'br-4', t: '4px' },
        { v: 'br-5', t: '5px' },
        { v: 'br-6', t: '6px' },
        { v: 'br-7', t: '7px' },
        { v: 'br-8', t: '8px' },
        { v: 'br-9', t: '9px' },
        { v: 'br-10', t: '10px' },
        { v: 'br-11', t: '11px' },
        { v: 'br-12', t: '12px' },
        { v: 'br-13', t: '13px' },
        { v: 'br-14', t: '14px' },
        { v: 'br-15', t: '15px' },
        { v: 'br-16', t: '16px' },
        { v: 'br-17', t: '17px' },
        { v: 'br-18', t: '18px' },
        { v: 'br-19', t: '19px' },
        { v: 'br-20', t: '20px' },
        { v: 'br-21', t: '21px' },
        { v: 'br-22', t: '22px' },
        { v: 'br-23', t: '23px' },
        { v: 'br-24', t: '24px' },
        { v: 'br-25', t: '25px' },
    ],
};
