// text_effects  yes_no justify align  gap  size  shadow  radius
export const options = {
  bg: [
    { v: 'bg-deep-blue-l5', t: 'Deep Blue Lighter 5' },
    { v: 'bg-deep-blue-l4', t: 'Deep Blue Lighter 4' },
    { v: 'bg-deep-blue-l3', t: 'Deep Blue Lighter 3' },
    { v: 'bg-deep-blue-l2', t: 'Deep Blue Lighter 2' },
    { v: 'bg-deep-blue-l1', t: 'Deep Blue Lighter 1' },
    { v: 'bg-deep-blue', t: 'Deep Blue' },
    { v: 'bg-deep-blue-d1', t: 'Deep Blue Darken 1' },
    { v: 'bg-deep-blue-d2', t: 'Deep Blue Darken 2' },
    { v: 'bg-deep-blue-d3', t: 'Deep Blue Darken 3' },
    { v: 'bg-deep-blue-d4', t: 'Deep Blue Darken 4' },
    { v: 'bg-deep-blue-d5', t: 'Deep Blue Darken 5' },
    { v: 'bg-blue-l5', t: 'Blue Lighter 5' },
    { v: 'bg-blue-l4', t: 'Blue Lighter 4' },
    { v: 'bg-blue-l3', t: 'Blue Lighter 3' },
    { v: 'bg-blue-l2', t: 'Blue Lighter 2' },
    { v: 'bg-blue-l1', t: 'Blue Lighter 1' },
    { v: 'bg-blue', t: 'Blue' },
    { v: 'bg-blue-d1', t: 'Blue Darken 1' },
    { v: 'bg-blue-d2', t: 'Blue Darken 2' },
    { v: 'bg-blue-d3', t: 'Blue Darken 3' },
    { v: 'bg-blue-d4', t: 'Blue Darken 4' },
    { v: 'bg-blue-d5', t: 'Blue Darken 5' },
    { v: 'bg-light-blue-l5', t: 'Light Blue Lighter 5' },
    { v: 'bg-light-blue-l4', t: 'Light Blue Lighter 4' },
    { v: 'bg-light-blue-l3', t: 'Light Blue Lighter 3' },
    { v: 'bg-light-blue-l2', t: 'Light Blue Lighter 2' },
    { v: 'bg-light-blue-l1', t: 'Light Blue Lighter 1' },
    { v: 'bg-light-blue', t: 'Light Blue' },
    { v: 'bg-light-blue-d1', t: 'Light Blue Darken 1' },
    { v: 'bg-light-blue-d2', t: 'Light Blue Darken 2' },
    { v: 'bg-light-blue-d3', t: 'Light Blue Darken 3' },
    { v: 'bg-light-blue-d4', t: 'Light Blue Darken 4' },
    { v: 'bg-light-blue-d5', t: 'Light Blue Darken 5' },
    { v: 'bg-red-l5', t: 'Red Lighter 5' },
    { v: 'bg-red-l4', t: 'Red Lighter 4' },
    { v: 'bg-red-l3', t: 'Red Lighter 3' },
    { v: 'bg-red-l2', t: 'Red Lighter 2' },
    { v: 'bg-red-l1', t: 'Red Lighter 1' },
    { v: 'bg-red', t: 'Red' },
    { v: 'bg-red-d1', t: 'Red Darken 1' },
    { v: 'bg-red-d2', t: 'Red Darken 2' },
    { v: 'bg-red-d3', t: 'Red Darken 3' },
    { v: 'bg-red-d4', t: 'Red Darken 4' },
    { v: 'bg-red-d5', t: 'Red Darken 5' },
    { v: 'bg-pink-l5', t: 'Pink Lighter 5' },
    { v: 'bg-pink-l4', t: 'Pink Lighter 4' },
    { v: 'bg-pink-l3', t: 'Pink Lighter 3' },
    { v: 'bg-pink-l2', t: 'Pink Lighter 2' },
    { v: 'bg-pink-l1', t: 'Pink Lighter 1' },
    { v: 'bg-pink', t: 'Pink' },
    { v: 'bg-pink-d1', t: 'Pink Darken 1' },
    { v: 'bg-pink-d2', t: 'Pink Darken 2' },
    { v: 'bg-pink-d3', t: 'Pink Darken 3' },
    { v: 'bg-pink-d4', t: 'Pink Darken 4' },
    { v: 'bg-pink-d5', t: 'Pink Darken 5' },
    { v: 'bg-purple-l5', t: 'Purple Lighter 5' },
    { v: 'bg-purple-l4', t: 'Purple Lighter 4' },
    { v: 'bg-purple-l3', t: 'Purple Lighter 3' },
    { v: 'bg-purple-l2', t: 'Purple Lighter 2' },
    { v: 'bg-purple-l1', t: 'Purple Lighter 1' },
    { v: 'bg-purple', t: 'Purple' },
    { v: 'bg-purple-d1', t: 'Purple Darken 1' },
    { v: 'bg-purple-d2', t: 'Purple Darken 2' },
    { v: 'bg-purple-d3', t: 'Purple Darken 3' },
    { v: 'bg-purple-d4', t: 'Purple Darken 4' },
    { v: 'bg-purple-d5', t: 'Purple Darken 5' },
    { v: 'bg-deep-purple-l5', t: 'Deep Purple Lighter 5' },
    { v: 'bg-deep-purple-l4', t: 'Deep Purple Lighter 4' },
    { v: 'bg-deep-purple-l3', t: 'Deep Purple Lighter 3' },
    { v: 'bg-deep-purple-l2', t: 'Deep Purple Lighter 2' },
    { v: 'bg-deep-purple-l1', t: 'Deep Purple Lighter 1' },
    { v: 'bg-deep-purple', t: 'Deep Purple' },
    { v: 'bg-deep-purple-d1', t: 'Deep Purple Darken 1' },
    { v: 'bg-deep-purple-d2', t: 'Deep Purple Darken 2' },
    { v: 'bg-deep-purple-d3', t: 'Deep Purple Darken 3' },
    { v: 'bg-deep-purple-d4', t: 'Deep Purple Darken 4' },
    { v: 'bg-deep-purple-d5', t: 'Deep Purple Darken 5' },
    { v: 'bg-indigo-l5', t: 'Indigo Lighter 5' },
    { v: 'bg-indigo-l4', t: 'Indigo Lighter 4' },
    { v: 'bg-indigo-l3', t: 'Indigo Lighter 3' },
    { v: 'bg-indigo-l2', t: 'Indigo Lighter 2' },
    { v: 'bg-indigo-l1', t: 'Indigo Lighter 1' },
    { v: 'bg-indigo', t: 'Indigo' },
    { v: 'bg-indigo-d1', t: 'Indigo Darken 1' },
    { v: 'bg-indigo-d2', t: 'Indigo Darken 2' },
    { v: 'bg-indigo-d3', t: 'Indigo Darken 3' },
    { v: 'bg-indigo-d4', t: 'Indigo Darken 4' },
    { v: 'bg-indigo-d5', t: 'Indigo Darken 5' },
    { v: 'bg-cyan-l5', t: 'Cyan Lighter 5' },
    { v: 'bg-cyan-l4', t: 'Cyan Lighter 4' },
    { v: 'bg-cyan-l3', t: 'Cyan Lighter 3' },
    { v: 'bg-cyan-l2', t: 'Cyan Lighter 2' },
    { v: 'bg-cyan-l1', t: 'Cyan Lighter 1' },
    { v: 'bg-cyan', t: 'Cyan' },
    { v: 'bg-cyan-d1', t: 'Cyan Darken 1' },
    { v: 'bg-cyan-d2', t: 'Cyan Darken 2' },
    { v: 'bg-cyan-d3', t: 'Cyan Darken 3' },
    { v: 'bg-cyan-d4', t: 'Cyan Darken 4' },
    { v: 'bg-cyan-d5', t: 'Cyan Darken 5' },
    { v: 'bg-teal-l5', t: 'Teal Lighter 5' },
    { v: 'bg-teal-l4', t: 'Teal Lighter 4' },
    { v: 'bg-teal-l3', t: 'Teal Lighter 3' },
    { v: 'bg-teal-l2', t: 'Teal Lighter 2' },
    { v: 'bg-teal-l1', t: 'Teal Lighter 1' },
    { v: 'bg-teal', t: 'Teal' },
    { v: 'bg-teal-d1', t: 'Teal Darken 1' },
    { v: 'bg-teal-d2', t: 'Teal Darken 2' },
    { v: 'bg-teal-d3', t: 'Teal Darken 3' },
    { v: 'bg-teal-d4', t: 'Teal Darken 4' },
    { v: 'bg-teal-d5', t: 'Teal Darken 5' },
    { v: 'bg-green-l5', t: 'Green Lighter 5' },
    { v: 'bg-green-l4', t: 'Green Lighter 4' },
    { v: 'bg-green-l3', t: 'Green Lighter 3' },
    { v: 'bg-green-l2', t: 'Green Lighter 2' },
    { v: 'bg-green-l1', t: 'Green Lighter 1' },
    { v: 'bg-green', t: 'Green' },
    { v: 'bg-green-d1', t: 'Green Darken 1' },
    { v: 'bg-green-d2', t: 'Green Darken 2' },
    { v: 'bg-green-d3', t: 'Green Darken 3' },
    { v: 'bg-green-d4', t: 'Green Darken 4' },
    { v: 'bg-green-d5', t: 'Green Darken 5' },
    { v: 'bg-light-green-l5', t: 'Light Green Lighter 5' },
    { v: 'bg-light-green-l4', t: 'Light Green Lighter 4' },
    { v: 'bg-light-green-l3', t: 'Light Green Lighter 3' },
    { v: 'bg-light-green-l2', t: 'Light Green Lighter 2' },
    { v: 'bg-light-green-l1', t: 'Light Green Lighter 1' },
    { v: 'bg-light-green', t: 'Light Green' },
    { v: 'bg-light-green-d1', t: 'Light Green Darken 1' },
    { v: 'bg-light-green-d2', t: 'Light Green Darken 2' },
    { v: 'bg-light-green-d3', t: 'Light Green Darken 3' },
    { v: 'bg-light-green-d4', t: 'Light Green Darken 4' },
    { v: 'bg-light-green-d5', t: 'Light Green Darken 5' },
    { v: 'bg-lime-l5', t: 'Lime Lighter 5' },
    { v: 'bg-lime-l4', t: 'Lime Lighter 4' },
    { v: 'bg-lime-l3', t: 'Lime Lighter 3' },
    { v: 'bg-lime-l2', t: 'Lime Lighter 2' },
    { v: 'bg-lime-l1', t: 'Lime Lighter 1' },
    { v: 'bg-lime', t: 'Lime' },
    { v: 'bg-lime-d1', t: 'Lime Darken 1' },
    { v: 'bg-lime-d2', t: 'Lime Darken 2' },
    { v: 'bg-lime-d3', t: 'Lime Darken 3' },
    { v: 'bg-lime-d4', t: 'Lime Darken 4' },
    { v: 'bg-lime-d5', t: 'Lime Darken 5' },
    { v: 'bg-yellow-l5', t: 'Yellow Lighter 5' },
    { v: 'bg-yellow-l4', t: 'Yellow Lighter 4' },
    { v: 'bg-yellow-l3', t: 'Yellow Lighter 3' },
    { v: 'bg-yellow-l2', t: 'Yellow Lighter 2' },
    { v: 'bg-yellow-l1', t: 'Yellow Lighter 1' },
    { v: 'bg-yellow', t: 'Yellow' },
    { v: 'bg-yellow-d1', t: 'Yellow Darken 1' },
    { v: 'bg-yellow-d2', t: 'Yellow Darken 2' },
    { v: 'bg-yellow-d3', t: 'Yellow Darken 3' },
    { v: 'bg-yellow-d4', t: 'Yellow Darken 4' },
    { v: 'bg-yellow-d5', t: 'Yellow Darken 5' },
    { v: 'bg-amber-l5', t: 'Amber Lighter 5' },
    { v: 'bg-amber-l4', t: 'Amber Lighter 4' },
    { v: 'bg-amber-l3', t: 'Amber Lighter 3' },
    { v: 'bg-amber-l2', t: 'Amber Lighter 2' },
    { v: 'bg-amber-l1', t: 'Amber Lighter 1' },
    { v: 'bg-amber', t: 'Amber' },
    { v: 'bg-amber-d1', t: 'Amber Darken 1' },
    { v: 'bg-amber-d2', t: 'Amber Darken 2' },
    { v: 'bg-amber-d3', t: 'Amber Darken 3' },
    { v: 'bg-amber-d4', t: 'Amber Darken 4' },
    { v: 'bg-amber-d5', t: 'Amber Darken 5' },
    { v: 'bg-orange-l5', t: 'Orange Lighter 5' },
    { v: 'bg-orange-l4', t: 'Orange Lighter 4' },
    { v: 'bg-orange-l3', t: 'Orange Lighter 3' },
    { v: 'bg-orange-l2', t: 'Orange Lighter 2' },
    { v: 'bg-orange-l1', t: 'Orange Lighter 1' },
    { v: 'bg-orange', t: 'Orange ' },
    { v: 'bg-orange-d1', t: 'Orange Darken 1' },
    { v: 'bg-orange-d2', t: 'Orange Darken 2' },
    { v: 'bg-orange-d3', t: 'Orange Darken 3' },
    { v: 'bg-orange-d4', t: 'Orange Darken 4' },
    { v: 'bg-orange-d5', t: 'Orange Darken 5' },
    { v: 'bg-deep-orange-l5', t: 'Deep Orange Lighter 5' },
    { v: 'bg-deep-orange-l4', t: 'Deep Orange Lighter 4' },
    { v: 'bg-deep-orange-l3', t: 'Deep Orange Lighter 3' },
    { v: 'bg-deep-orange-l2', t: 'Deep Orange Lighter 2' },
    { v: 'bg-deep-orange-l1', t: 'Deep Orange Lighter 1' },
    { v: 'bg-deep-orange', t: 'Deep Orange ' },
    { v: 'bg-deep-orange-d1', t: 'Deep Orange Darken 1' },
    { v: 'bg-deep-orange-d2', t: 'Deep Orange Darken 2' },
    { v: 'bg-deep-orange-d3', t: 'Deep Orange Darken 3' },
    { v: 'bg-deep-orange-d4', t: 'Deep Orange Darken 4' },
    { v: 'bg-deep-orange-d5', t: 'Deep Orange Darken 5' },
    { v: 'bg-brown-l5', t: 'Brown L-5' },
    { v: 'bg-brown-l4', t: 'Brown L-4' },
    { v: 'bg-brown-l3', t: 'Brown L-3' },
    { v: 'bg-brown-l2', t: 'Brown L-2' },
    { v: 'bg-brown-l1', t: 'Brown L-1' },
    { v: 'bg-brown', t: 'Brown' },
    { v: 'bg-brown-d1', t: 'Brown D-1' },
    { v: 'bg-brown-d2', t: 'Brown D-2' },
    { v: 'bg-brown-d3', t: 'Brown D-3' },
    { v: 'bg-brown-d4', t: 'Brown D-4' },
    { v: 'bg-brown-d5', t: 'Brown D-5' },
    { v: 'bg-blue-grey-l5', t: 'Blue Grey Lighter 5' },
    { v: 'bg-blue-grey-l4', t: 'Blue Grey Lighter 4' },
    { v: 'bg-blue-grey-l3', t: 'Blue Grey Lighter 3' },
    { v: 'bg-blue-grey-l2', t: 'Blue Grey Lighter 2' },
    { v: 'bg-blue-grey-l1', t: 'Blue Grey Lighter 1' },
    { v: 'bg-blue-grey', t: 'Blue Grey' },
    { v: 'bg-blue-grey-d1', t: 'Blue Grey Darken 1' },
    { v: 'bg-blue-grey-d2', t: 'Blue Grey Darken 2' },
    { v: 'bg-blue-grey-d3', t: 'Blue Grey Darken 3' },
    { v: 'bg-blue-grey-d4', t: 'Blue Grey Darken 4' },
    { v: 'bg-blue-grey-d5', t: 'Blue Grey Darken 5' },
    { v: 'bg-black-alpha-1', t: 'Black Alpha 1' },
    { v: 'bg-black-alpha-2', t: 'Black Alpha 2' },
    { v: 'bg-black-alpha-3', t: 'Black Alpha 3' },
    { v: 'bg-black-alpha-4', t: 'Black Alpha 4' },
    { v: 'bg-black-alpha-5', t: 'Black Alpha 5' },
    { v: 'bg-black-alpha-6', t: 'Black Alpha 6' },
    { v: 'bg-black-alpha-7', t: 'Black Alpha 7' },
    { v: 'bg-black-alpha-8', t: 'Black Alpha 8' },
    { v: 'bg-black-alpha-9', t: 'Black Alpha 9' },
    { v: 'bg-black-alpha-95', t: 'Black Alpha 95' },
    { v: 'bg-black', t: 'Black' },
    { v: 'bg-white-alpha-1', t: 'White Alpha 1' },
    { v: 'bg-white-alpha-2', t: 'White Alpha 2' },
    { v: 'bg-white-alpha-3', t: 'White Alpha 3' },
    { v: 'bg-white-alpha-4', t: 'White Alpha 4' },
    { v: 'bg-white-alpha-5', t: 'White Alpha 5' },
    { v: 'bg-white-alpha-6', t: 'White Alpha 6' },
    { v: 'bg-white-alpha-7', t: 'White Alpha 7' },
    { v: 'bg-white-alpha-8', t: 'White Alpha 8' },
    { v: 'bg-white-alpha-9', t: 'White Alpha 9' },
    { v: 'bg-white-alpha-95', t: 'White Alpha 95' },
    { v: 'bg-white', t: 'White' },
  ],
  col: [
    { v: 'tx-deep-blue-l2', t: 'Deep Blue Lighter 2' },
    { v: 'tx-deep-blue-l1', t: 'Deep Blue Lighter 1' },
    { v: 'tx-deep-blue', t: 'Deep Blue' },
    { v: 'tx-deep-blue-d1', t: 'Deep Blue Darken 1' },
    { v: 'tx-deep-blue-d2', t: 'Deep Blue Darken 2' },
    { v: 'tx-blue-l2', t: 'Blue Lighter 2' },
    { v: 'tx-blue-l1', t: 'Blue Lighter 1' },
    { v: 'tx-blue', t: 'Blue' },
    { v: 'tx-blue-d1', t: 'Blue Darken 1' },
    { v: 'tx-blue-d2', t: 'Blue Darken 2' },
    { v: 'tx-light-blue-l2', t: 'Light Blue Lighter 2' },
    { v: 'tx-light-blue-l1', t: 'Light Blue Lighter 1' },
    { v: 'tx-light-blue', t: 'Light Blue' },
    { v: 'tx-light-blue-d1', t: 'Light Blue Darken 1' },
    { v: 'tx-light-blue-d2', t: 'Light Blue Darken 2' },
    { v: 'tx-red-l2', t: 'Red Lighter 2' },
    { v: 'tx-red-l1', t: 'Red Lighter 1' },
    { v: 'tx-red', t: 'Red' },
    { v: 'tx-red-d1', t: 'Red Darken 1' },
    { v: 'tx-red-d2', t: 'Red Darken 2' },
    { v: 'tx-pink-l2', t: 'Pink Lighter 2' },
    { v: 'tx-pink-l1', t: 'Pink Lighter 1' },
    { v: 'tx-pink', t: 'Pink' },
    { v: 'tx-pink-d1', t: 'Pink Darken 1' },
    { v: 'tx-pink-d2', t: 'Pink Darken 2' },
    { v: 'tx-purple-l2', t: 'Purple Lighter 2' },
    { v: 'tx-purple-l1', t: 'Purple Lighter 1' },
    { v: 'tx-purple', t: 'Purple' },
    { v: 'tx-purple-d1', t: 'Purple Darken 1' },
    { v: 'tx-purple-d2', t: 'Purple Darken 2' },
    { v: 'tx-deep-purple-l2', t: 'Deep Purple Lighter 2' },
    { v: 'tx-deep-purple-l1', t: 'Deep Purple Lighter 1' },
    { v: 'tx-deep-purple', t: 'Deep Purple' },
    { v: 'tx-deep-purple-d1', t: 'Deep Purple Darken 1' },
    { v: 'tx-deep-purple-d2', t: 'Deep Purple Darken 2' },
    { v: 'tx-indigo-l2', t: 'Indigo Lighter 2' },
    { v: 'tx-indigo-l1', t: 'Indigo Lighter 1' },
    { v: 'tx-indigo', t: 'Indigo' },
    { v: 'tx-indigo-d1', t: 'Indigo Darken 1' },
    { v: 'tx-indigo-d2', t: 'Indigo Darken 2' },
    { v: 'tx-cyan-l2', t: 'Cyan Lighter 2' },
    { v: 'tx-cyan-l1', t: 'Cyan Lighter 1' },
    { v: 'tx-cyan', t: 'Cyan' },
    { v: 'tx-cyan-d1', t: 'Cyan Darken 1' },
    { v: 'tx-cyan-d2', t: 'Cyan Darken 2' },
    { v: 'tx-teal-l2', t: 'Teal Lighter 2' },
    { v: 'tx-teal-l1', t: 'Teal Lighter 1' },
    { v: 'tx-teal', t: 'Teal' },
    { v: 'tx-teal-d1', t: 'Teal Darken 1' },
    { v: 'tx-teal-d2', t: 'Teal Darken 2' },
    { v: 'tx-green-l2', t: 'Green Lighter 2' },
    { v: 'tx-green-l1', t: 'Green Lighter 1' },
    { v: 'tx-green', t: 'Green' },
    { v: 'tx-green-d1', t: 'Green Darken 1' },
    { v: 'tx-green-d2', t: 'Green Darken 2' },
    { v: 'tx-light-green-l2', t: 'Light Green Lighter 2' },
    { v: 'tx-light-green-l1', t: 'Light Green Lighter 1' },
    { v: 'tx-light-green', t: 'Light Green' },
    { v: 'tx-light-green-d1', t: 'Light Green Darken 1' },
    { v: 'tx-light-green-d2', t: 'Light Green Darken 2' },
    { v: 'tx-lime-l2', t: 'Lime Lighter 2' },
    { v: 'tx-lime-l1', t: 'Lime Lighter 1' },
    { v: 'tx-lime', t: 'Lime' },
    { v: 'tx-lime-d1', t: 'Lime Darken 1' },
    { v: 'tx-lime-d2', t: 'Lime Darken 2' },
    { v: 'tx-yellow-l2', t: 'Yellow Lighter 2' },
    { v: 'tx-yellow-l1', t: 'Yellow Lighter 1' },
    { v: 'tx-yellow', t: 'Yellow' },
    { v: 'tx-yellow-d1', t: 'Yellow Darken 1' },
    { v: 'tx-yellow-d2', t: 'Yellow Darken 2' },
    { v: 'tx-amber-l2', t: 'Amber Lighter 2' },
    { v: 'tx-amber-l1', t: 'Amber Lighter 1' },
    { v: 'tx-amber', t: 'Amber' },
    { v: 'tx-amber-d1', t: 'Amber Darken 1' },
    { v: 'tx-amber-d2', t: 'Amber Darken 2' },
    { v: 'tx-orange-l2', t: 'Orange Lighter 2' },
    { v: 'tx-orange-l1', t: 'Orange Lighter 1' },
    { v: 'tx-orange', t: 'Orange ' },
    { v: 'tx-orange-d1', t: 'Orange Darken 1' },
    { v: 'tx-orange-d2', t: 'Orange Darken 2' },
    { v: 'tx-deep-orange-l2', t: 'Deep Orange Lighter 2' },
    { v: 'tx-deep-orange-l1', t: 'Deep Orange Lighter 1' },
    { v: 'tx-deep-orange', t: 'Deep Orange ' },
    { v: 'tx-deep-orange-d1', t: 'Deep Orange Darken 1' },
    { v: 'tx-deep-orange-d2', t: 'Deep Orange Darken 2' },
    { v: 'tx-brown-l2', t: 'Brown L-2' },
    { v: 'tx-brown-l1', t: 'Brown L-1' },
    { v: 'tx-brown', t: 'Brown' },
    { v: 'tx-brown-d1', t: 'Brown D-1' },
    { v: 'tx-brown-d2', t: 'Brown D-2' },
    { v: 'tx-blue-grey-l2', t: 'Blue Grey Lighter 2' },
    { v: 'tx-blue-grey-l1', t: 'Blue Grey Lighter 1' },
    { v: 'tx-blue-grey', t: 'Blue Grey' },
    { v: 'tx-blue-grey-d1', t: 'Blue Grey Darken 1' },
    { v: 'tx-blue-grey-d2', t: 'Blue Grey Darken 2' },
    { v: 'tx-black-alpha-2', t: 'Black Alpha 2' },
    { v: 'tx-black-alpha-4', t: 'Black Alpha 4' },
    { v: 'tx-black-alpha-6', t: 'Black Alpha 6' },
    { v: 'tx-black-alpha-8', t: 'Black Alpha 8' },
    { v: 'tx-black', t: 'Black' },
    { v: 'tx-white-alpha-2', t: 'White Alpha 2' },
    { v: 'tx-white-alpha-4', t: 'White Alpha 4' },
    { v: 'tx-white-alpha-6', t: 'White Alpha 6' },
    { v: 'tx-white-alpha-8', t: 'White Alpha 8' },
    { v: 'tx-white', t: 'White' },
  ],
};
